### ISSUE TITLE
Cannot use weekday numeric function Argument 1must be of the type array, string given

### ISSUE THREAD

**Issue by webdevilopers** [oroinc/doctrine-extensions#4]
I configured `weekday` as described in the docs:

``` yaml
doctrine:
    orm:
        dql:
            numeric_functions:
                weekday:      Oro\ORM\Query\AST\Functions\SimpleFunction
```

Excerpt from my DQL:

``` php
        $qb = $this->_em->createQueryBuilder();
        $qb->select(array(
                'WEEKDAY(tke.date) AS weekDay'
            ));
```

The error I get:
**Catchable Fatal Error: Argument 1 passed to Oro\ORM\Query\AST\Platform\Functions\PlatformFunctionNode::__construct() must be of the type array, string given, called in /.../vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php on line 3389**
